-- ntc color names
Colors = {
    Putty = '#D7C484',
    Roti = '#C9A654',
    Driftwood = '#B3854D',
    Copper = '#BB7844',
    CapePalliser = '#B36B42',
    SantaFe = '#B3664D',
    Amulet = '#669977',
    Dingley = '#77824A',
    GladeGreen = '#5F865F',
    Shadow = '#80744D',
    GoBen = '#7A6D52',
    Flint = '#6E665E',
    IronsideGray = '#6B6461',
    Coffee = '#736659',
    TobaccoBrown = '#675642',
    Tundora = '#484441',
    Masala = '#463939',
    Dune = '#3B3330',
    GreenKelp = '#252F1E',
    Zeus = '#24211E',
    Shark = '#212121',
    Woodsmoke = '#121212',
}

--[[ "This file was generated by Fennel. Do not modify." ]]
local theme = {}
theme["Normal"] = {bg = Colors.Zeus, fg = Colors.Putty}
theme["Identifier"] = {link = "Normal"}
theme["Variable"] = {link = "Identifier"}
theme["@variable"] = {link = "Variable"}
theme["@lsp.type.parameter"] = {link = "Identifier"}
theme["@lsp.type.property"] = {link = "Identifier"}
theme["@lsp.type.variable"] = {link = "Identifier"}
theme["@namespace"] = {link = "Identifier"}
theme["@parameter"] = {link = "Identifier"}
theme["@text.reference"] = {link = "Identifier"}
theme["DelimiterLight"] = {link = "Normal"}
theme["@punctuation.bracket"] = {link = "DelimiterLight"}
theme["Statement"] = {fg = Colors.GladeGreen}
theme["Keyword"] = {fg = Colors.GladeGreen}
theme["@keyword"] = {link = "Keyword"}
theme["Conditional"] = {link = "Statement"}
theme["Repeat"] = {link = "Statement"}
theme["Label"] = {link = "Statement"}
theme["Exception"] = {link = "Statement"}
theme["PreProc"] = {link = "Statement"}
theme["Include"] = {link = "Statement"}
theme["Define"] = {link = "Statement"}
theme["Macro"] = {link = "Statement"}
theme["PreCondit"] = {link = "Statement"}
theme["@preproc"] = {link = "Preproc"}
theme["Function"] = {fg = Colors.Dingley}
theme["@function"] = {link = "Function"}
theme["@method"] = {link = "Function"}
theme["@function.builtin"] = {link = "Function"}
theme["@lsp.type.decorator"] = {link = "Function"}
theme["@lsp.type.function"] = {link = "Function"}
theme["@lsp.type.method"] = {link = "Function"}
theme["Type"] = {fg = Colors.Dingley}
theme["Structure"] = {link = "Type"}
theme["StorageClass"] = {link = "Type"}
theme["Typedef"] = {link = "Type"}
theme["@type"] = {link = "Type"}
theme["@lsp.type.type"] = {link = "Type"}
theme["String"] = {fg = Colors.Driftwood}
theme["@string"] = {link = "String"}
theme["Number"] = {fg = Colors.SantaFe}
theme["@number"] = {link = "Number"}
theme["Float"] = {link = "Number"}
theme["Boolean"] = {link = "Number"}
theme["@boolean"] = {link = "Boolean"}
theme["Field"] = {fg = Colors.Copper}
theme["@field"] = {link = "Field"}
theme["@property"] = {link = "Field"}
theme["Constant"] = {fg = Colors.Copper}
theme["Character"] = {link = "Constant"}
theme["@lsp.type.enumMember"] = {link = "Constant"}
theme["vimHiAttrib"] = {link = "Constant"}
theme["Comment"] = {fg = Colors.Flint}
theme["@comment"] = {link = "Comment"}
theme["@html.comment"] = {link = "Comment"}
theme["@lsp.type.comment"] = {link = "Comment"}
theme["@text.literal"] = {link = "Comment"}
theme["CtrlPLinePre"] = {link = "Comment"}
theme["LspCodeLens"] = {link = "Comment"}
theme["Operator"] = {fg = Colors.Amulet}
theme["Delimiter"] = {fg = Colors.Shadow}
theme["NvimParenthesis"] = {link = "Delimiter"}
theme["@punctuation"] = {link = "Delimiter"}
theme["Special"] = {fg = Colors.Copper}
theme["Debug"] = {link = "Special"}
theme["SpecialChar"] = {link = "Special"}
theme["SpecialComment"] = {link = "Special"}
theme["Tag"] = {link = "Special"}
theme["@constant.builtin"] = {link = "Special"}
theme["@constructor"] = {link = "Special"}
theme["@punctuation.special"] = {link = "Special"}
theme["NonText"] = {fg = Colors.GoBen}
theme["EndOfBuffer"] = {link = "NonText"}
theme["Whitespace"] = {link = "NonText"}
theme["Visual"] = {bg = Colors.Dune}
theme["Cursor"] = {bg = Colors.Putty, fg = Colors.Shark}
theme["CursorColumn"] = {bg = Colors.Zeus}
theme["CursorLine"] = {link = "CursorColumn"}
theme["LineNr"] = {fg = Colors.Dingley}
theme["LineNrAbove"] = {fg = Colors.Coffee}
theme["LineNrBelow"] = {link = "LineNrAbove"}
theme["CursorLineNr"] = {link = "LineNr"}
theme["TermCursor"] = {reverse = true}
theme["Search"] = {bg = Colors.GladeGreen, fg = Colors.Shark}
theme["CurSearch"] = {link = "Search"}
theme["QuickFixLine"] = {link = "Search"}
theme["Substitute"] = {link = "Search"}
theme["IncSearch"] = {bg = Colors.Copper, fg = Colors.Shark}
theme["Error"] = {bg = Colors.SantaFe, fg = Colors.Putty}
theme["ErrorMsg"] = {fg = Colors.CapePalliser}
theme["WarningMsg"] = {fg = Colors.CapePalliser}
theme["MoreMsg"] = {bold = true, fg = Colors.GladeGreen}
theme["ModeMsg"] = {bold = true, fg = Colors.Dingley}
theme["Question"] = {fg = Colors.GladeGreen}
theme["Bold"] = {bold = true}
theme["Italic"] = {italic = true}
theme["Underlined"] = {fg = Colors.Dingley, underline = true}
theme["@text.underline"] = {link = "Underlined"}
theme["@text.uri"] = {link = "Underlined"}
theme["Title"] = {bold = true, fg = Colors.CapePalliser}
theme["@text.title"] = {link = "Title"}
theme["ColorColumn"] = {bg = Colors.Zeus}
theme["MatchParen"] = {bg = Colors.Masala, fg = Colors.Putty}
theme["Folded"] = {fg = Colors.CapePalliser}
theme["Ignore"] = {fg = Colors.Tundora}
theme["Conceal"] = {link = "Ignore"}
theme["SpecialKey"] = {link = "Normal"}
theme["NvimSpacing"] = {link = "Normal"}
theme["DiffText"] = {link = "Visual"}
theme["DiffAdd"] = {bg = Colors.GladeGreen, fg = Colors.Shark}
theme["@text.diff.add"] = {link = "DiffAdd"}
theme["Added"] = {fg = Colors.GladeGreen}
theme["DiffAdded"] = {link = "Added"}
theme["@diff.plus"] = {link = "Added"}
theme["DiffChange"] = {bg = Colors.TobaccoBrown, fg = Colors.Shark}
theme["@text.diff.change"] = {link = "DiffChange"}
theme["Changed"] = {fg = Colors.TobaccoBrown}
theme["DiffChanged"] = {link = "Changed"}
theme["@diff.delta"] = {link = "Changed"}
theme["DiffDelete"] = {bg = Colors.CapePalliser, fg = Colors.Shark}
theme["@text.diff.delete"] = {link = "DiffDelete"}
theme["Removed"] = {fg = Colors.CapePalliser}
theme["DiffRemoved"] = {link = "Removed"}
theme["@diff.minus"] = {link = "Removed"}
theme["NormalFloat"] = {link = "Normal"}
theme["FloatBorder"] = {fg = Colors.Dingley}
theme["FloatTitle"] = {bold = true, fg = Colors.GladeGreen}
theme["Pmenu"] = {link = "Normal"}
theme["PmenuExtra"] = {link = "Pmenu"}
theme["PmenuKind"] = {link = "Pmenu"}
theme["PmenuSbar"] = {fg = Colors.IronsideGray}
theme["PmenuThumb"] = {bg = Colors.Putty, fg = Colors.Putty}
theme["PmenuSel"] = {bg = Colors.Dingley, fg = Colors.Shark}
theme["PmenuExtraSel"] = {link = "PmenuSel"}
theme["PmenuKindSel"] = {link = "PmenuSel"}
theme["StatusLine"] = {bg = Colors.Zeus, bold = true, fg = Colors.Putty}
theme["MsgSeparator"] = {link = "StatusLine"}
theme["StatusLineNC"] = {bg = Colors.Zeus, bold = true, fg = Colors.Coffee}
theme["TabLine"] = {bg = Colors.Woodsmoke, fg = Colors.IronsideGray}
theme["TabLineFill"] = {bg = Colors.Zeus, fg = Colors.Driftwood}
theme["TabLineSel"] = {bg = Colors.Dingley, bold = true, fg = Colors.Woodsmoke}
theme["TabLineSelSep"] = {bg = Colors.Zeus, bold = true, fg = Colors.Dingley}
theme["TabLineSep"] = {bg = Colors.Zeus, fg = Colors.Woodsmoke}
theme["Directory"] = {link = "Type"}
theme["netrwExe"] = {link = "Changed"}
theme["netrwClassify"] = {link = "Comment"}
theme["SpellBad"] = {fg = Colors.TobaccoBrown, sp = Colors.Putty}
theme["SpellCap"] = {fg = Colors.GladeGreen, sp = Colors.Putty}
theme["SpellLocal"] = {fg = Colors.Copper, sp = Colors.Putty}
theme["SpellRare"] = {fg = Colors.CapePalliser, sp = Colors.Putty}
theme["helpSectionDelim"] = {link = "Comment"}
theme["helpHyperTextEntry"] = {link = "Statement"}
theme["helpExample"] = {link = "String"}
theme["helpHeadline"] = {link = "Title"}
theme["helpHyperTextJump"] = {link = "Underlined"}
theme["helpURL"] = {link = "Underlined"}
theme["DiagnosticDeprecated"] = {sp = Colors.TobaccoBrown, strikethrough = true}
theme["DiagnosticError"] = {fg = Colors.SantaFe}
theme["DiagnosticErrorFloating"] = {link = "DiagnosticError"}
theme["DiagnosticSignError"] = {link = "DiagnosticError"}
theme["DiagnosticVirtualTextError"] = {link = "DiagnosticError"}
theme["DiagnosticUnderlineError"] = {underline = true}
theme["DiagnosticWarn"] = {fg = Colors.Copper}
theme["DiagnosticFloatingWarn"] = {link = "DiagnosticWarn"}
theme["DiagnosticSignWarn"] = {link = "DiagnosticWarn"}
theme["DiagnosticVirtualTextWarn"] = {link = "DiagnosticWarn"}
theme["DiagnosticUnderlineWarn"] = {underline = true}
theme["DiagnosticHint"] = {fg = Colors.Flint}
theme["DiagnosticFloatingHint"] = {link = "DiagnosticHint"}
theme["DiagnosticSignHint"] = {link = "DiagnosticHint"}
theme["DiagnosticVirtualTextHint"] = {link = "DiagnosticHint"}
theme["DiagnosticUnderlineHint"] = {underline = true}
theme["DiagnosticInfo"] = {fg = Colors.Roti}
theme["DiagnosticFloatingInfo"] = {link = "DiagnosticInfo"}
theme["DiagnosticSignInfo"] = {link = "DiagnosticInfo"}
theme["DiagnosticVirtualTextInfo"] = {link = "DiagnosticInfo"}
theme["DiagnosticUnderlineInfo"] = {underline = true}
theme["DiagnosticOk"] = {fg = Colors.Dingley}
theme["DiagnosticFloatingOk"] = {link = "DiagnosticOk"}
theme["DiagnosticSignOk"] = {link = "DiagnosticOk"}
theme["DiagnosticVirtualTextOk"] = {link = "DiagnosticOk"}
theme["Todo"] = {bg = Colors.Putty, fg = Colors.Zeus}
theme["@text.todo"] = {link = "Todo"}
theme["htmlLink"] = {link = "Underlined"}
theme["markdownBold"] = {link = "Bold"}
theme["markdownItalic"] = {link = "Italic"}
theme["@markup.heading"] = {link = "Special"}
theme["@markup.raw.block.markdown"] = {link = "Special"}
theme["@markup.list"] = {link = "Operator"}
theme["@markup.link"] = {fg = Colors.Dingley, underline = true}
theme["@punctuation.special.markdown"] = {link = "Comment"}
theme["@property.lua"] = {link = "Normal"}
theme["LazyNormal"] = {link = "Normal"}
theme["LazyButtonActive"] = {bg = Colors.Dingley, fg = Colors.Shark}
theme["LazyH1"] = {fg = Colors.Dingley}
theme["LazyH2"] = {fg = Colors.Dingley}
theme["LazySpecial"] = {fg = Colors.Roti}
theme["MasonHeaderSecondary"] = {link = "LazyButtonActive"}
theme["MasonHighlightBlock"] = {link = "LazyButtonActive"}
theme["FzfLuaNormal"] = {link = "Normal"}
theme["FzfLuaTitle"] = {link = "FloatTitle"}
theme["FzfLuaBorder"] = {link = "FloatBorder"}
theme["FzfLuaCursor"] = {link = "Cursor"}
theme["FzfLuaCursorLine"] = {link = "CursorLine"}
theme["FzfLuaCursorLineNr"] = {link = "CursorLineNr"}
theme["FzfLuaSearch"] = {link = "IncSearch"}
theme["FzfLuaScrollFloatEmpty"] = {link = "PmenuSbar"}
theme["FzfLuaScrollFloatFull"] = {link = "PmenuThumb"}
theme["MiniTablineCurrent"] = {link = "TabLineSel"}
theme["MiniTablineHidden"] = {link = "Normal"}
theme["MiniTablineVisible"] = {link = "MiniTablineHidden"}
theme["MiniTablineModifiedCurrent"] = {bg = Colors.GladeGreen, bold = true, fg = Colors.Zeus}
theme["MiniTablineModifiedHidden"] = {link = "TabLineFill"}
theme["MiniTablineModifiedVisible"] = {link = "MiniTablineModifiedHidden"}
theme["MiniTablineTabpageSection"] = {link = "IncSearch"}
theme["MiniJump2dSpot"] = {link = "TabLineSel"}
theme["IblIndent"] = {fg = Colors.GreenKelp}
theme["GitSignsAdd"] = {link = "Added"}
theme["GitSignsChange"] = {link = "Changed"}
theme["GitSignsDelete"] = {link = "Removed"}
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.g.colors_name = "darkearth"
vim.o.background = "dark"
for group, attr in pairs(theme) do
  vim.api.nvim_set_hl(0, group, attr)
end
return nil
